apiVersion: apps/v1
kind: Deployment
metadata:
  name: planadevopschallenge1
  labels:
    app: planadevopschallenge1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planadevopschallenge1
  template:
    metadata:
      labels:
        app: planadevopschallenge1
    spec:
      containers:
      - name: planadevopschallenge1
        image: davitelesfranca/planadevopschallenge1:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"