apiVersion: v1
kind: Service
metadata:
  name: planadevopschallenge1
  labels:
    app: planadevopschallenge1
spec:
  selector:
    app: planadevopschallenge1
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort